/****************************************************************************/
/* PRELIMINARIES*/
/****************************************************************************/

/*CREATING DATABASE FOR THIS ASSIGNMENT*/
CREATE DATABASE ONLINE_BOOKSTORE_ASSIGNMENT;
USE ONLINE_BOOKSTORE_ASSIGNMENT;

/****************************************************************************/
/*CREATING ENTITES*/
/****************************************************************************/

/*ADDRESS ENTITY 1*/
CREATE TABLE ADDRESS (
  ADDRESS_ID char(7) NOT NULL,
  STREET_NUMBER int(100) NOT NULL,
  STREET_NAME varchar(100) NOT NULL,
  CITY_ID char(100) NOT NULL
);

/*AUTHOR ENTITY 2*/
CREATE TABLE AUTHOR (
  AUTH_ID char(5) NOT NULL,
  AUTH_NAME varchar(50) NOT NULL
) ;

/*BOOK ENTITY 3*/
CREATE TABLE BOOK (
  BOOK_ID char(7) NOT NULL,
  TITLE varchar(50) NOT NULL,
  ISBN bigint(13) NOT NULL,
  QTY int(4) NOT NULL,
  PRICE float(5,2) NOT NULL,
  PUB_DATE date NOT NULL,
  PUB_ID char(5) NOT NULL
);

/*BOOK_AUTHOR ENTITY 4*/
CREATE TABLE BOOK_AUTHOR (
  BOOK_ID char(7) NOT NULL,
  AUTH_ID char(5) NOT NULL
);

/*BOOK_GENRE ENTITY 5*/
CREATE TABLE BOOK_GENRE (
  BOOK_ID char(7) NOT NULL,
  GEN_ID char(3) NOT NULL
);

/*CITY ENTITY 6*/
CREATE TABLE CITY (
  CITY_ID char(100) NOT NULL,
  CITY_NAME varchar(100) NOT NULL
);

/*CUSTOMER ENTITY 7*/
CREATE TABLE CUSTOMER (
  CUSTOMER_ID char(8) NOT NULL,
  FIRST_NAME varchar(50) NOT NULL,
  LAST_NAME varchar(50) NOT NULL,
  EMAIL varchar(50) NOT NULL
);

/*GENRE ENTITY 8*/
CREATE TABLE GENRE (
  GEN_ID char(3) NOT NULL,
  GEN_NAME varchar(50) NOT NULL
);

/*PUBLISHER ENTITY 9*/
CREATE TABLE PUBLISHER (
  PUB_ID char(5) NOT NULL,
  PUB_NAME varchar(50) NOT NULL
);

/*REVIEW ENTITY 10*/
CREATE TABLE REVIEW (
  REV_ID char(11) NOT NULL,
  RATING int(1) NOT NULL,
  COMMENTS varchar(250) DEFAULT NULL,
  CUSTOMER_ID char(8) NOT NULL
);

/*SHIPPING_METHOD ENTITY 11*/
CREATE TABLE SHIPPING_METHOD (
  METHOD_ID char(2) NOT NULL,
  METHOD_NAME varchar(100) NOT NULL
  COST FLOAT(4,2) NOT NULL
);

/*SHOPPING_CART ENTITY 12*/
CREATE TABLE SHOPPING_CART (
  CART_ID char(12) NOT NULL,
  ORDER_DATE date NOT NULL,
  CUSTOMER_ID char(8) NOT NULL,
  METHOD_ID char(2) NOT NULL,
  ADDRESS_ID char(7) NOT NULL
);

/*ORDER_LINE ENTITY 13*/
CREATE TABLE ORDER_LINE (
	LINE_ID CHAR(10) NOT NULL PRIMARY KEY,
	CART_ID CHAR(12) NOT NULL,
	BOOK_ID CHAR(7) NOT NULL,
	ORD_QTY INT(3)  NOT NULL
);

/*_TRANSACTION_ ENTITY 14*/
CREATE TABLE _TRANSACTION_ (
	TRANSACTION_ID CHAR(12) NOT NULL PRIMARY KEY,
	CART_ID CHAR(12) NOT NULL,
	TOTAL_PRICE FLOAT(7,2) NOT NULL
);

/****************************************************************************/
/*ADDING INDEXES TO THE ENTITIES*/
/****************************************************************************/

/*Indexes for table `ADDRESS`*/
ALTER TABLE ADDRESS
  ADD PRIMARY KEY (ADDRESS_ID),
  ADD KEY CITY_ID (CITY_ID);

/*Indexes for table `AUTHOR`*/
ALTER TABLE AUTHOR
  ADD PRIMARY KEY (AUTH_ID);

/*Indexes for table `BOOK`*/
ALTER TABLE BOOK
  ADD PRIMARY KEY (BOOK_ID),
  ADD KEY PUB_ID (PUB_ID);

/*Indexes for table `BOOK_AUTHOR`*/
ALTER TABLE BOOK_AUTHOR
  ADD PRIMARY KEY (BOOK_ID,AUTH_ID),
  ADD KEY AUTH_ID (AUTH_ID);

/*Indexes for table `BOOK_GENRE`*/
ALTER TABLE BOOK_GENRE
  ADD PRIMARY KEY (BOOK_ID,GEN_ID),
  ADD KEY GEN_ID (GEN_ID);

/*Indexes for table `CITY`*/
ALTER TABLE CITY
  ADD PRIMARY KEY (CITY_ID);

/*Indexes for table `CUSTOMER`*/
ALTER TABLE CUSTOMER
  ADD PRIMARY KEY (CUSTOMER_ID);

/*Indexes for table `GENRE`*/
ALTER TABLE GENRE
  ADD PRIMARY KEY (GEN_ID);

/*Indexes for table `PUBLISHER`*/
ALTER TABLE PUBLISHER
  ADD PRIMARY KEY (PUB_ID);

/*Indexes for table `REVIEW`*/
ALTER TABLE REVIEW
  ADD PRIMARY KEY (REV_ID),
  ADD KEY CUSTOMER_ID (CUSTOMER_ID);

/*Indexes for table `SHIPPING_METHOD`*/
ALTER TABLE SHIPPING_METHOD
  ADD PRIMARY KEY (METHOD_ID);

/*Indexes for table `SHOPPING_CART`*/
ALTER TABLE SHOPPING_CART
  ADD PRIMARY KEY (CART_ID),
  ADD KEY CUSTOMER_ID (CUSTOMER_ID),
  ADD KEY METHOD_ID (METHOD_ID),
  ADD KEY ADDRESS_ID (ADDRESS_ID);
  

/****************************************************************************/
/*ADDING CONSTRAINTS TO THE ENTITIES*/
/****************************************************************************/

/*Constraints for table `ADDRESS`*/
ALTER TABLE ADDRESS
  ADD CONSTRAINT address_ibfk_1 FOREIGN KEY (CITY_ID) REFERENCES CITY (CITY_ID);

/*Constraints for table `BOOK`*/
ALTER TABLE BOOK
  ADD CONSTRAINT book_ibfk_1 FOREIGN KEY (PUB_ID) REFERENCES PUBLISHER (PUB_ID);

/*Constraints for table `BOOK_AUTHOR`*/
ALTER TABLE BOOK_AUTHOR
  ADD CONSTRAINT book_author_ibfk_1 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID),
  ADD CONSTRAINT book_author_ibfk_2 FOREIGN KEY (AUTH_ID) REFERENCES AUTHOR (AUTH_ID);

/*Constraints for table `BOOK_GENRE`*/
ALTER TABLE BOOK_GENRE
  ADD CONSTRAINT book_genre_ibfk_1 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID),
  ADD CONSTRAINT book_genre_ibfk_2 FOREIGN KEY (GEN_ID) REFERENCES GENRE (GEN_ID);

/*Constraints for table `REVIEW`*/
ALTER TABLE REVIEW
  ADD CONSTRAINT review_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);

/*Constraints for table `SHOPPING_CART`*/
ALTER TABLE SHOPPING_CART
  ADD CONSTRAINT shopping_cart_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
  ADD CONSTRAINT shopping_cart_ibfk_2 FOREIGN KEY (METHOD_ID) REFERENCES SHIPPING_METHOD (METHOD_ID),
  ADD CONSTRAINT shopping_cart_ibfk_3 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);

/*Constraints for table ORDER_LINE*/
ALTER TABLE ORDER_LINE
  ADD CONSTRAINT SHOPPING_CART_IBFK1 FOREIGN KEY (CART_ID) REFERENCES SHOPPING_CART (CART_ID),
  ADD CONSTRAINT BOOK_IBFK2 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID);
  

/*Constraints for table _TRANSACTION_*/
ALTER TABLE _TRANSACTION_
ADD CONSTRAINT SHOPPING_CART FOREIGN KEY (CART_ID) REFERENCES SHOPPING_CART (CART_ID);

